import { NonNeverFn } from "plgg/index";

/**
 * Type-safe point-free composition: compose a sequence of functions into a
 * single function. Variadic — 2–20 functions (only the 2-function arity is
 * shown here; the higher arities are equivalent).
 */
export function flow<A, B>(
  ab: (a: A) => NonNeverFn<B>,
): (a: A) => NonNeverFn<B>;
/** @internal */
export function flow<A, B, C>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
): (a: A) => NonNeverFn<C>;
/** @internal */
export function flow<A, B, C, D>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
): (a: A) => NonNeverFn<D>;
/** @internal */
export function flow<A, B, C, D, E>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
): (a: A) => NonNeverFn<E>;
/** @internal */
export function flow<A, B, C, D, E, F>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
): (a: A) => NonNeverFn<F>;
/** @internal */
export function flow<A, B, C, D, E, F, G>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
): (a: A) => NonNeverFn<G>;
/** @internal */
export function flow<A, B, C, D, E, F, G, H>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
): (a: A) => NonNeverFn<H>;
/** @internal */
export function flow<A, B, C, D, E, F, G, H, I>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
): (a: A) => NonNeverFn<I>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
): (a: A) => NonNeverFn<J>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
): (a: A) => NonNeverFn<K>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
): (a: A) => NonNeverFn<L>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
): (a: A) => NonNeverFn<M>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
  mn: (m: M) => NonNeverFn<N>,
): (a: A) => NonNeverFn<N>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
  mn: (m: M) => NonNeverFn<N>,
  no: (n: N) => NonNeverFn<O>,
): (a: A) => NonNeverFn<O>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
  mn: (m: M) => NonNeverFn<N>,
  no: (n: N) => NonNeverFn<O>,
  op: (o: O) => NonNeverFn<P>,
): (a: A) => NonNeverFn<P>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
  mn: (m: M) => NonNeverFn<N>,
  no: (n: N) => NonNeverFn<O>,
  op: (o: O) => NonNeverFn<P>,
  pq: (p: P) => NonNeverFn<Q>,
): (a: A) => NonNeverFn<Q>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
  mn: (m: M) => NonNeverFn<N>,
  no: (n: N) => NonNeverFn<O>,
  op: (o: O) => NonNeverFn<P>,
  pq: (p: P) => NonNeverFn<Q>,
  qr: (q: Q) => NonNeverFn<R>,
): (a: A) => NonNeverFn<R>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
  mn: (m: M) => NonNeverFn<N>,
  no: (n: N) => NonNeverFn<O>,
  op: (o: O) => NonNeverFn<P>,
  pq: (p: P) => NonNeverFn<Q>,
  qr: (q: Q) => NonNeverFn<R>,
  rs: (r: R) => NonNeverFn<S>,
): (a: A) => NonNeverFn<S>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
  mn: (m: M) => NonNeverFn<N>,
  no: (n: N) => NonNeverFn<O>,
  op: (o: O) => NonNeverFn<P>,
  pq: (p: P) => NonNeverFn<Q>,
  qr: (q: Q) => NonNeverFn<R>,
  rs: (r: R) => NonNeverFn<S>,
  st: (s: S) => NonNeverFn<T>,
): (a: A) => NonNeverFn<T>;
/** @internal */
export function flow<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
>(
  ab: (a: A) => NonNeverFn<B>,
  bc: (b: B) => NonNeverFn<C>,
  cd: (c: C) => NonNeverFn<D>,
  de: (d: D) => NonNeverFn<E>,
  ef: (e: E) => NonNeverFn<F>,
  fg: (f: F) => NonNeverFn<G>,
  gh: (g: G) => NonNeverFn<H>,
  hi: (h: H) => NonNeverFn<I>,
  ij: (i: I) => NonNeverFn<J>,
  jk: (j: J) => NonNeverFn<K>,
  kl: (k: K) => NonNeverFn<L>,
  lm: (l: L) => NonNeverFn<M>,
  mn: (m: M) => NonNeverFn<N>,
  no: (n: N) => NonNeverFn<O>,
  op: (o: O) => NonNeverFn<P>,
  pq: (p: P) => NonNeverFn<Q>,
  qr: (q: Q) => NonNeverFn<R>,
  rs: (r: R) => NonNeverFn<S>,
  st: (s: S) => NonNeverFn<T>,
  tu: (t: T) => NonNeverFn<U>,
): (a: A) => NonNeverFn<U>;

/*
 * Composes async functions into sequential execution pipeline
 * Overloads enable type inference between composition steps
 */
export function flow(
  ...fns: ReadonlyArray<
    (a: unknown) => NonNeverFn<unknown>
  >
): (input: unknown) => unknown {
  return (input: unknown) =>
    fns.reduce((acc, fn) => fn(acc), input);
}
