import { NonNeverFn } from "plgg/index";

/**
 * Type-safe function composition: thread a value left-to-right through a
 * sequence of functions. Variadic — a value followed by 2–20 functions (only
 * the 2-argument arity is shown here; the higher arities are equivalent).
 */
export function pipe<A, B>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
): B;
/** @internal */
export function pipe<A, B, C>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
): C;
/** @internal */
export function pipe<A, B, C, D>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
): D;
/** @internal */
export function pipe<A, B, C, D, E>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
): E;
/** @internal */
export function pipe<A, B, C, D, E, F>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
): F;
/** @internal */
export function pipe<A, B, C, D, E, F, G>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
): G;
/** @internal */
export function pipe<A, B, C, D, E, F, G, H>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
): H;
/** @internal */
export function pipe<A, B, C, D, E, F, G, H, I>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
): I;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
): J;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
): K;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
): L;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
): M;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
  mn: NonNeverFn<(m: M) => N>,
): N;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
  mn: NonNeverFn<(m: M) => N>,
  no: NonNeverFn<(n: N) => O>,
): O;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
  mn: NonNeverFn<(m: M) => N>,
  no: NonNeverFn<(n: N) => O>,
  op: NonNeverFn<(o: O) => P>,
): P;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
  mn: NonNeverFn<(m: M) => N>,
  no: NonNeverFn<(n: N) => O>,
  op: NonNeverFn<(o: O) => P>,
  pq: NonNeverFn<(p: P) => Q>,
): Q;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
  mn: NonNeverFn<(m: M) => N>,
  no: NonNeverFn<(n: N) => O>,
  op: NonNeverFn<(o: O) => P>,
  pq: NonNeverFn<(p: P) => Q>,
  qr: NonNeverFn<(q: Q) => R>,
): R;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
  mn: NonNeverFn<(m: M) => N>,
  no: NonNeverFn<(n: N) => O>,
  op: NonNeverFn<(o: O) => P>,
  pq: NonNeverFn<(p: P) => Q>,
  qr: NonNeverFn<(q: Q) => R>,
  rs: NonNeverFn<(r: R) => S>,
): S;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
  mn: NonNeverFn<(m: M) => N>,
  no: NonNeverFn<(n: N) => O>,
  op: NonNeverFn<(o: O) => P>,
  pq: NonNeverFn<(p: P) => Q>,
  qr: NonNeverFn<(q: Q) => R>,
  rs: NonNeverFn<(r: R) => S>,
  st: NonNeverFn<(s: S) => T>,
): T;
/** @internal */
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
>(
  a: A,
  ab: NonNeverFn<(a: A) => B>,
  bc: NonNeverFn<(b: B) => C>,
  cd: NonNeverFn<(c: C) => D>,
  de: NonNeverFn<(d: D) => E>,
  ef: NonNeverFn<(e: E) => F>,
  fg: NonNeverFn<(f: F) => G>,
  gh: NonNeverFn<(g: G) => H>,
  hi: NonNeverFn<(h: H) => I>,
  ij: NonNeverFn<(i: I) => J>,
  jk: NonNeverFn<(j: J) => K>,
  kl: NonNeverFn<(k: K) => L>,
  lm: NonNeverFn<(l: L) => M>,
  mn: NonNeverFn<(m: M) => N>,
  no: NonNeverFn<(n: N) => O>,
  op: NonNeverFn<(o: O) => P>,
  pq: NonNeverFn<(p: P) => Q>,
  qr: NonNeverFn<(q: Q) => R>,
  rs: NonNeverFn<(r: R) => S>,
  st: NonNeverFn<(s: S) => T>,
  tu: NonNeverFn<(t: T) => U>,
): U;

/**
 * Implementation function that pipes value through functions sequentially.
 */
export function pipe(
  value: unknown,
  ...fns: ReadonlyArray<(a: unknown) => unknown>
): unknown {
  return fns.reduce((acc, fn) => fn(acc), value);
}
