name: Fix
type: Fix
labels: ["fix"]
title: Fix ***
description: A change made to correct an error, bug, or unintended behavior in existing code.
body:
  - type: markdown
    attributes:
      value: |
        Write a concise and accurate title reflecting the purpose of this issue, and this doubles as the pull request title.

        -----------------------------------------------
  ## Bug Report
  - type: textarea
    id: situation
    attributes:
      label: 1. Situation
      description: Describe the objective situation of the issue and steps to reproduce it.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: 2. Cause
      description: If the cause is known, please describe it. If not, leave it blank and update later.
      value: "*To be filled in later"
  - type: textarea
    id: affected_range
    attributes:
      label: 3. Scope of Impact (Timeframe, Affected Users, etc.)
      description: (Optional) Describe the period during which the issue occurred and the affected users or areas.
  - type: textarea
    id: caused_from
    attributes:
      label: 4. Cause of the Bug
      description: Provide the URL of the issue that introduced the bug.
      value: |
        1. (Issue URL)

  - type: markdown
    attributes:
      value: |
        -----------------------------------------------

        ## Post-Issue Steps

        ### 1. Set additional fields for GitHub Projects

        For a repository with the initial setup completed, issues will be added and automatically linked to relevant projects. Before proceeding, ensure all fields are properly configured. For fields that require numeric input, follow these guidelines:

        * Effort (person-days)
          * Enter an estimated amount of time it would take an average developer participating in this project. Assume 1 person-day = 8 hours, with a minimum of 0.25 person-days (2 hours) and a maximum of 10 person-days (2 weeks). If it exceeds this range, consider splitting the issue.
        * Difficulty
          - 4 = High - Tasks where it's unclear where to start.
          - 3 = Moderately High - Tasks requiring independent problem understanding and issue identification.
          - 2 = Moderately Low - Tasks that can be clarified through investigation or understanding specifications.
          - 1 = Low - Tasks where what needs to be done is already clear.

        ### 2. Assign a responsible developer

        By setting assignee to the issue, automatically triggers the GitHub Action creating a pull request linked to the issue. Typically, development continues by checking out the branch associated with this pull request.

        ### 3. Write specification and test plan

        These should be documented in the pull request (not the issue).
