// The guide's single information-architecture + home-data
// instance: pure data validated through plgg-press's
// `defineSite` boundary caster. This replaces the old
// VitePress `defineConfig` — there is deliberately no
// dependency on the `vitepress` package here. plgg-press
// owns the
// `SiteConfig` TYPE and the `defineSite` validator; this
// file supplies only the guide's values (ported verbatim
// from the former `.vitepress/config.ts` and `index.md`)
// and splices in the per-package API sidebar emitted by
// `scripts/gen-api.mjs`.
import {
  existsSync,
  readFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { defineSite } from "plgg-press";

// GitHub Pages serves a project site under `/<repo>/`; the
// deploy workflow sets DOCS_BASE so links resolve there,
// while local dev/preview stay at root. plgg-press's href
// helper is the single rewrite site downstream.
const base = process.env.DOCS_BASE ?? "/";

// The exhaustive, per-package API reference is
// auto-generated by `scripts/gen-api.mjs`, which writes
// `api/typedoc-sidebar.json` as a per-package map: each
// package name maps to `{ link, items }` (its landing link
// plus one leaf per category). Load it when present so each
// package group gets its API reference spliced in; with no
// generation it falls back to an empty map, leaving the
// package groups prose-only.
const guideRoot = dirname(
  fileURLToPath(import.meta.url),
);
const apiSidebarFile = join(
  guideRoot,
  "api",
  "typedoc-sidebar.json",
);

// One manifest entry per package: `{ link, items }` where
// each `items` leaf is a `{ text, link }` category page.
type ApiEntry = {
  link: string;
  items: ReadonlyArray<{
    text: string;
    link: string;
  }>;
};
type ApiManifest = Record<string, ApiEntry>;

const isApiEntry = (
  value: unknown,
): value is ApiEntry =>
  typeof value === "object" &&
  value !== null &&
  "link" in value &&
  "items" in value;

// Read and shape the generated manifest into a typed
// `ApiManifest` without escape hatches: parse to `unknown`,
// then keep only the well-formed `{ link, items }` entries.
const loadApiManifest = (): ApiManifest => {
  if (!existsSync(apiSidebarFile)) {
    return {};
  }
  const parsed: unknown = JSON.parse(
    readFileSync(apiSidebarFile, "utf8"),
  );
  if (
    typeof parsed !== "object" ||
    parsed === null
  ) {
    return {};
  }
  const out: Record<string, ApiEntry> = {};
  for (const [key, value] of Object.entries(
    parsed,
  )) {
    if (isApiEntry(value)) {
      out[key] = {
        link: value.link,
        items: value.items.map((item) => ({
          text: item.text,
          link: item.link,
        })),
      };
    }
  }
  return out;
};

const generatedApi = loadApiManifest();

// A sidebar node as authored here: every node carries an
// explicit `items` array (the leaf case is `[]`) so it
// validates against plgg-press's `SidebarItem`, whose
// `items` is required and whose `link` is optional.
type Node = {
  text: string;
  link?: string;
  items: ReadonlyArray<Node>;
};

const leaf = (
  text: string,
  link: string,
): Node => ({ text, link, items: [] });

// One top-level sidebar group per package. The group header
// links to nothing itself; its children are the Guide
// (prose) then the API reference. Order: the featured trio
// (plgg, plgg-http, plgg-router) first, then the rest, then
// the example tutorial (prose-only — `api: false`).
type PackageGroup = {
  key: string;
  text: string;
  overview: string;
  docs?: ReadonlyArray<Node>;
  api?: false;
};

const PACKAGE_GROUPS: ReadonlyArray<PackageGroup> =
  [
    {
      key: "plgg",
      text: "plgg (core)",
      overview: "/packages/plgg/",
      docs: [
        leaf(
          "Values & effects",
          "/packages/plgg/values-effects",
        ),
        leaf(
          "Structures & errors",
          "/packages/plgg/structures-errors",
        ),
      ],
    },
    {
      key: "plgg-http",
      text: "plgg-http",
      overview: "/packages/plgg-http",
    },
    {
      key: "plgg-router",
      text: "plgg-router",
      overview: "/packages/plgg-router",
    },
    {
      key: "plgg-server",
      text: "plgg-server",
      overview: "/packages/plgg-server",
    },
    {
      key: "plgg-fetch",
      text: "plgg-fetch",
      overview: "/packages/plgg-fetch",
    },
    {
      key: "plgg-view",
      text: "plgg-view",
      overview: "/packages/plgg-view",
    },
    {
      key: "plgg-sql",
      text: "plgg-sql",
      overview: "/packages/plgg-sql",
    },
    {
      key: "plgg-kit",
      text: "plgg-kit",
      overview: "/packages/plgg-kit",
    },
    {
      key: "plgg-foundry",
      text: "plgg-foundry",
      overview: "/packages/plgg-foundry",
    },
    {
      key: "plgg-test",
      text: "plgg-test",
      overview: "/packages/plgg-test",
    },
    {
      key: "example",
      text: "example (tutorial)",
      overview: "/packages/example",
      api: false,
    },
  ];

// The "Guide" node spliced at the START of a package group:
// the package's prose. With extra prose pages (only plgg
// core today) it nests them beneath the Overview; otherwise
// it is a plain link to the single prose page.
const guideNode = (group: PackageGroup): Node => {
  const docs = group.docs ?? [];
  return {
    text: "Guide",
    link: group.overview,
    items: docs,
  };
};

// The "API reference" node spliced at the END of a package
// group: a link to the package's API landing, with one leaf
// per category when the package's reference spans more than
// one. Returns `[]` when generation has not run or the
// package opts out, so the group degrades to prose-only.
const apiReferenceNode = (
  group: PackageGroup,
): ReadonlyArray<Node> => {
  if (group.api === false) {
    return [];
  }
  const entry = generatedApi[group.key];
  if (!entry) {
    return [];
  }
  return [
    {
      text: "API reference",
      link: entry.link,
      items: entry.items.map((item) =>
        leaf(item.text, item.link),
      ),
    },
  ];
};

// Assemble one package's top-level sidebar group: the Guide
// (prose) then the API reference, the two reading paths side
// by side.
const packageGroup = (
  group: PackageGroup,
): {
  text: string;
  items: ReadonlyArray<Node>;
} => ({
  text: group.text,
  items: [
    guideNode(group),
    ...apiReferenceNode(group),
  ],
});

// Information architecture for the plgg family guide: the
// nav and sidebar tree below name every page, ported
// verbatim from the former `.vitepress/config.ts`.
const config = {
  base,
  title: "plgg",
  description:
    "The official guide for plgg and the " +
    "plgg family — a TypeScript toolkit where " +
    "web development is one typed pipeline: " +
    "Option/Result, errors as data, " +
    "runtime-neutral, built from scratch.",
  nav: [
    leaf("Guide", "/getting-started"),
    leaf("Packages", "/packages/plgg/"),
    leaf("API", "/api/"),
    leaf("GitHub", "https://github.com/qmu/plgg"),
  ],
  sidebar: [
    {
      text: "Guide",
      items: [
        leaf(
          "Getting started",
          "/getting-started",
        ),
        {
          text: "Core concepts",
          link: "/concepts/",
          items: [
            leaf(
              "Tagged data (Box)",
              "/concepts/tagged-data",
            ),
            leaf(
              "Option, not null",
              "/concepts/option",
            ),
            leaf(
              "Result, not throw",
              "/concepts/result",
            ),
            leaf(
              "Validation with cast",
              "/concepts/validation",
            ),
            leaf(
              "Async with proc",
              "/concepts/async",
            ),
            leaf(
              "Exhaustive match",
              "/concepts/match",
            ),
            leaf(
              "Data-last composition",
              "/concepts/composition",
            ),
          ],
        },
      ],
    },
    ...PACKAGE_GROUPS.map(packageGroup),
    {
      text: "Contributing",
      items: [
        leaf(
          "Doc conventions",
          "/contributing/conventions",
        ),
      ],
    },
  ],
  social: [
    {
      icon: "github",
      link: "https://github.com/qmu/plgg",
    },
  ],
  // The landing-page DATA (spike §6b): the theme renders
  // these generically into the hero + feature grid. The
  // hero name reuses the site `title` (item 15), so home
  // carries only the headline + tagline + actions/features
  // ported from the former `index.md` frontmatter.
  home: {
    title:
      "Web development as one typed pipeline",
    tagline:
      "A TypeScript family built from scratch " +
      "on a single idea — values flow through " +
      "pure functions, errors are data, and the " +
      "same program runs on the server and in " +
      "the browser.",
    actions: [
      {
        text: "Get started",
        link: "/getting-started",
      },
      {
        text: "Core concepts",
        link: "/concepts/",
      },
      {
        text: "View on GitHub",
        link: "https://github.com/qmu/plgg",
      },
    ],
    features: [
      {
        title: "Option, not null",
        details:
          "Absence is a value you must handle, " +
          "never a null that slips through. The " +
          "compiler keeps the gaps honest.",
      },
      {
        title: "Result, not throw",
        details:
          "Errors travel as data through the " +
          "pipeline and fold to one vocabulary " +
          "at the edge, instead of unwinding the " +
          "stack.",
      },
      {
        title: "One pipeline, end to end",
        details:
          "pipe / cast / proc / flow compose " +
          "validation, effects, and transforms " +
          "into a single data-last expression.",
      },
      {
        title: "Runtime-neutral core",
        details:
          "plgg-http models request/response as " +
          "pure data; plgg-server and plgg-fetch " +
          "are symmetric peers over the same " +
          "model.",
      },
      {
        title: "Server and client, one program",
        details:
          "plgg-view's Elm-Architecture " +
          "Model/update/view renders both " +
          "server-side (SSR) and in the browser " +
          "(CSR) from the same source.",
      },
      {
        title: "Built from scratch",
        details:
          "Every package — HTTP, router, view, " +
          "SQL, AI orchestration — is built on " +
          "plgg, so the same patterns hold " +
          "across the whole family.",
      },
    ],
  },
  // dev.allowedHosts (spike item 7): the extra Host headers
  // plgg-press's node:http dev server accepts. localhost for
  // local work; plgg-guide.qmu.dev for the port-5181
  // Cloudflare tunnel.
  dev: {
    allowedHosts: [
      "localhost",
      "plgg-guide.qmu.dev",
    ],
  },
};

// Author-time validation through the boundary caster: an Ok
// is the typed `SiteConfig`, an Err names the offending
// field. Exported so a check / plgg-press can assert it.
export const site = defineSite(config);

// The raw config DATA is the default export plgg-press's
// `loadConfig` reads and validates through `defineSite` at
// build/dev time (the one place untrusted config crosses
// into the typed core).
export default config;
