import { defineConfig } from "vitepress";
import {
  existsSync,
  readFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// The exhaustive, per-package API reference is auto-generated by
// `scripts/gen-api.mjs` (run by `npm run build` before `vitepress build`),
// which writes `api/typedoc-sidebar.json`. Load it when present so the
// generated subtree fills the "API reference" section; in plain `vitepress dev`
// (no generation) it gracefully falls back to just the Overview link.
const guideRoot = dirname(
  dirname(fileURLToPath(import.meta.url)),
);
const apiSidebarFile = join(
  guideRoot,
  "api",
  "typedoc-sidebar.json",
);
const generatedApiGroups = existsSync(
  apiSidebarFile,
)
  ? JSON.parse(
      readFileSync(apiSidebarFile, "utf8"),
    )
  : [];

// GitHub Pages serves a project site under `/<repo>/`; the deploy workflow sets
// DOCS_BASE so links resolve there, while local dev/preview stay at root.
const base = process.env.DOCS_BASE ?? "/";

// Information architecture for the plgg family guide.
//
// This file is the *contract* every later content
// ticket (T2–T8) fills in: the nav and sidebar tree
// below name every page, and each section is owned by
// one ticket. Keep the tree comprehensive — one node
// per package + concept — so no later ticket has to
// restructure navigation.
export default defineConfig({
  base,
  title: "plgg",
  description:
    "The official guide for plgg and the " +
    "plgg family — a TypeScript toolkit where " +
    "web development is one typed pipeline: " +
    "Option/Result, errors as data, " +
    "runtime-neutral, built from scratch.",
  themeConfig: {
    nav: [
      { text: "Guide", link: "/getting-started" },
      {
        text: "Packages",
        link: "/packages/plgg/",
      },
      { text: "API", link: "/api/" },
      {
        text: "GitHub",
        link: "https://github.com/qmu/plgg",
      },
    ],
    sidebar: [
      {
        text: "Guide",
        items: [
          {
            text: "Getting started",
            link: "/getting-started",
          },
          {
            text: "Core concepts",
            link: "/concepts/",
            items: [
              {
                text: "Tagged data (Box)",
                link: "/concepts/tagged-data",
              },
              {
                text: "Option, not null",
                link: "/concepts/option",
              },
              {
                text: "Result, not throw",
                link: "/concepts/result",
              },
              {
                text: "Validation with cast",
                link: "/concepts/validation",
              },
              {
                text: "Async with proc",
                link: "/concepts/async",
              },
              {
                text: "Exhaustive match",
                link: "/concepts/match",
              },
              {
                text: "Data-last composition",
                link: "/concepts/composition",
              },
            ],
          },
        ],
      },
      {
        text: "Packages",
        items: [
          {
            text: "plgg (core)",
            link: "/packages/plgg/",
            items: [
              {
                text: "Values & effects",
                link: "/packages/plgg/values-effects",
              },
              {
                text: "Structures & errors",
                link: "/packages/plgg/structures-errors",
              },
            ],
          },
          {
            text: "plgg-http",
            link: "/packages/plgg-http",
          },
          {
            text: "plgg-server",
            link: "/packages/plgg-server",
          },
          {
            text: "plgg-fetch",
            link: "/packages/plgg-fetch",
          },
          {
            text: "plgg-router",
            link: "/packages/plgg-router",
          },
          {
            text: "plgg-view",
            link: "/packages/plgg-view",
          },
          {
            text: "plgg-sql",
            link: "/packages/plgg-sql",
          },
          {
            text: "plgg-kit",
            link: "/packages/plgg-kit",
          },
          {
            text: "plgg-foundry",
            link: "/packages/plgg-foundry",
          },
          {
            text: "example (tutorial)",
            link: "/packages/example",
          },
        ],
      },
      {
        text: "API reference",
        items: [
          {
            text: "Overview",
            link: "/api/",
          },
          ...generatedApiGroups,
        ],
      },
      {
        text: "Contributing",
        items: [
          {
            text: "Doc conventions",
            link: "/contributing/conventions",
          },
        ],
      },
    ],
    socialLinks: [
      {
        icon: "github",
        link: "https://github.com/qmu/plgg",
      },
    ],
  },
});
