import { defineConfig } from "vitepress";
import {
  existsSync,
  readFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// The exhaustive, per-package API reference is auto-generated by
// `scripts/gen-api.mjs` (run by `npm run build` before `vitepress build`),
// which writes `api/typedoc-sidebar.json` as a per-package map: each package
// name maps to `{ link, items }` (its landing link plus one leaf per category).
// Load it when present so each package group gets its API reference spliced in;
// in plain `vitepress dev` (no generation) it gracefully falls back to an empty
// map, leaving the package groups prose-only.
const guideRoot = dirname(
  dirname(fileURLToPath(import.meta.url)),
);
const apiSidebarFile = join(
  guideRoot,
  "api",
  "typedoc-sidebar.json",
);
const generatedApi = existsSync(apiSidebarFile)
  ? JSON.parse(
      readFileSync(apiSidebarFile, "utf8"),
    )
  : {};

// The plgg family, as one top-level sidebar group per package. The group header
// links to the package's main prose page; any further prose pages plus the
// generated API reference (looked up in `generatedApi`) nest beneath it. Order:
// the featured trio (plgg, plgg-http, plgg-router) first, then the rest, then
// the example tutorial (prose-only — `api: false`, no generated reference).
const PACKAGE_GROUPS = [
  {
    key: "plgg",
    text: "plgg (core)",
    overview: "/packages/plgg/",
    docs: [
      {
        text: "Values & effects",
        link: "/packages/plgg/values-effects",
      },
      {
        text: "Structures & errors",
        link: "/packages/plgg/structures-errors",
      },
    ],
  },
  {
    key: "plgg-http",
    text: "plgg-http",
    overview: "/packages/plgg-http",
  },
  {
    key: "plgg-router",
    text: "plgg-router",
    overview: "/packages/plgg-router",
  },
  {
    key: "plgg-server",
    text: "plgg-server",
    overview: "/packages/plgg-server",
  },
  {
    key: "plgg-fetch",
    text: "plgg-fetch",
    overview: "/packages/plgg-fetch",
  },
  {
    key: "plgg-view",
    text: "plgg-view",
    overview: "/packages/plgg-view",
  },
  {
    key: "plgg-sql",
    text: "plgg-sql",
    overview: "/packages/plgg-sql",
  },
  {
    key: "plgg-kit",
    text: "plgg-kit",
    overview: "/packages/plgg-kit",
  },
  {
    key: "plgg-foundry",
    text: "plgg-foundry",
    overview: "/packages/plgg-foundry",
  },
  {
    key: "example",
    text: "example (tutorial)",
    overview: "/packages/example",
    api: false,
  },
];

// The "API reference" node spliced at the END of a package group: a link to the
// package's API landing, with one collapsed leaf per category when the package's
// reference spans more than one. Returns `[]` when generation has not run (dev)
// or the package has no reference, so the group degrades to prose-only.
const apiReferenceNode = (group) => {
  if (group.api === false) {
    return [];
  }
  const entry = generatedApi[group.key];
  if (!entry) {
    return [];
  }
  const node = {
    text: "API reference",
    link: entry.link,
  };
  return entry.items && entry.items.length
    ? [
        {
          ...node,
          collapsed: true,
          items: entry.items,
        },
      ]
    : [node];
};

// The "Guide" node spliced at the START of a package group: the package's prose,
// surfaced as a first-class sidebar item parallel to "API reference". When the
// package has extra prose pages (only plgg core today) it is a collapsible
// subgroup linking the Overview with those pages beneath; otherwise it is a
// plain link to the single prose page.
const guideNode = (group) => {
  const node = {
    text: "Guide",
    link: group.overview,
  };
  const docs = group.docs ?? [];
  return docs.length
    ? { ...node, collapsed: true, items: docs }
    : node;
};

// Assemble one package's top-level sidebar group: its children are the Guide
// (prose) then the API reference, the two reading paths shown side by side. The
// group header itself toggles the group — the Guide child carries the prose link.
const packageGroup = (group) => ({
  text: group.text,
  items: [
    guideNode(group),
    ...apiReferenceNode(group),
  ],
});

// GitHub Pages serves a project site under `/<repo>/`; the deploy workflow sets
// DOCS_BASE so links resolve there, while local dev/preview stay at root.
const base = process.env.DOCS_BASE ?? "/";

// Information architecture for the plgg family guide.
//
// This file is the *contract* every later content
// ticket (T2–T8) fills in: the nav and sidebar tree
// below name every page, and each section is owned by
// one ticket. Keep the tree comprehensive — one node
// per package + concept — so no later ticket has to
// restructure navigation.
export default defineConfig({
  base,
  // The dev server is reached through the Cloudflare tunnel hostname; Vite
  // blocks unknown Host headers by default, so allow it (localhost/127.0.0.1
  // stay allowed automatically). Affects `vitepress dev` only.
  vite: {
    server: {
      allowedHosts: ["plgg-guide.qmu.dev"],
    },
  },
  title: "plgg",
  description:
    "The official guide for plgg and the " +
    "plgg family — a TypeScript toolkit where " +
    "web development is one typed pipeline: " +
    "Option/Result, errors as data, " +
    "runtime-neutral, built from scratch.",
  themeConfig: {
    nav: [
      { text: "Guide", link: "/getting-started" },
      {
        text: "Packages",
        link: "/packages/plgg/",
      },
      { text: "API", link: "/api/" },
      {
        text: "GitHub",
        link: "https://github.com/qmu/plgg",
      },
    ],
    sidebar: [
      {
        text: "Guide",
        items: [
          {
            text: "Getting started",
            link: "/getting-started",
          },
          {
            text: "Core concepts",
            link: "/concepts/",
            items: [
              {
                text: "Tagged data (Box)",
                link: "/concepts/tagged-data",
              },
              {
                text: "Option, not null",
                link: "/concepts/option",
              },
              {
                text: "Result, not throw",
                link: "/concepts/result",
              },
              {
                text: "Validation with cast",
                link: "/concepts/validation",
              },
              {
                text: "Async with proc",
                link: "/concepts/async",
              },
              {
                text: "Exhaustive match",
                link: "/concepts/match",
              },
              {
                text: "Data-last composition",
                link: "/concepts/composition",
              },
            ],
          },
        ],
      },
      ...PACKAGE_GROUPS.map(packageGroup),
      {
        text: "Contributing",
        items: [
          {
            text: "Doc conventions",
            link: "/contributing/conventions",
          },
        ],
      },
    ],
    socialLinks: [
      {
        icon: "github",
        link: "https://github.com/qmu/plgg",
      },
    ],
  },
});
