name: Run Tests
on:
  pull_request:
    types: [review_requested, synchronize, labeled]
  push:
    branches:
      - "main"
permissions:
  issues: write
  pull-requests: write

jobs:
  run-tests:
    if: |
      (github.event.action == 'review_requested' ||
      (github.event.action == 'labeled' && github.event.label.name == 'ci-testing') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'ci-testing'))) ||
      (github.event_name == 'push')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/github-script@v6
        name: Set 'ci-testing' label
        if: github.event.action == 'review_requested'
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ci-testing"]
            })
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'src/plgg/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        working-directory: src/plgg
        
      - name: Run TypeScript compilation check
        run: npx tsc --noEmit
        working-directory: src/plgg
        
      - name: Run tests
        run: npm test
        working-directory: src/plgg
        
      - name: Build library
        run: npm run build
        working-directory: src/plgg
        
      - name: Run tests with coverage
        run: npm run coverage
        working-directory: src/plgg
