import { TextClass } from "plgg-token-metering/domain/model/TextClass";

/**
 * The published article's own sample manifest and measured rows, frozen as a
 * fixture so the accuracy claims in this package's README can be re-checked by
 * running the tests — with no API key, no network, and no provider call.
 *
 * Source: docs/research-reports/token-metering-comparison (qmu/research),
 * manifest `tm-v1`, run 2026-07-17T03:02:34.699Z.
 * The sample texts are copied from that repo's `samples.ts`, whose header
 * states they are frozen for reuse by this package and are self-authored (no
 * third-party corpus, so no external text license enters this repo).
 *
 * `chars` and `utf8Bytes` are the article's OWN recorded values, not
 * recomputed here. `article.spec.ts` asserts that each copied text measures
 * exactly those values, which is what proves the copy is faithful — during this
 * fixture's construction that check caught a real corruption of `code-01`,
 * where a naive edit had rewritten text inside the sample.
 */

/** The pinned manifest version the accuracy is stated over. */
export const SAMPLES_VERSION = "tm-v1";

/** The agreed accuracy target, percent. Met by two of the four families. */
export const ACCURACY_TARGET_PCT = 5;

/** The instant of the measuring run. */
export const MEASURED_AT =
  "2026-07-17T03:02:34.699Z";

export type ArticleSample = Readonly<{
  id: string;
  textClass: TextClass;
  role: "calibration" | "holdout";
  text: string;
}>;

/**
 * The 30 pinned samples: 10 english, 10 japanese, 10 code.
 */
export const SAMPLES: ReadonlyArray<ArticleSample> =
  [
    {
      id: "en-01",
      textClass: "english",
      role: "calibration",
      text: "Token counting decides what an API call costs before the call is made. A metering layer that cannot count tokens cannot attribute spend to the principal who caused it.",
    },
    {
      id: "en-02",
      textClass: "english",
      role: "holdout",
      text: "The invoice arrived three weeks late, and by then the finance team had already closed the quarter. Nobody could say which department had approved the original purchase order, so the amount sat in a suspense account until the next audit.",
    },
    {
      id: "en-03",
      textClass: "english",
      role: "calibration",
      text: "Rate limits are enforced per organization, not per user. When a burst of requests exceeds the configured ceiling, the gateway returns a 429 response with a Retry-After header, and well-behaved clients back off exponentially with jitter before retrying the failed request.",
    },
    {
      id: "en-04",
      textClass: "english",
      role: "holdout",
      text: "She walked along the harbor wall at dusk, counting the fishing boats as they came in. Seventeen tonight — two fewer than yesterday. The wind had turned during the afternoon and smelled of rain, and the gulls had gone quiet, which the old men on the pier always said meant a storm before morning. She pulled her coat tighter and kept walking toward the lighthouse.",
    },
    {
      id: "en-05",
      textClass: "english",
      role: "calibration",
      text: "Q3 revenue grew 14% year over year to $8.2M, driven by a 31% increase in enterprise subscriptions. Gross margin held at 71%. Operating expenses rose 9%, primarily headcount in engineering (12 hires) and the SOC 2 Type II audit fee. Net retention reached 118%.",
    },
    {
      id: "en-06",
      textClass: "english",
      role: "holdout",
      text: "To reset the device, hold the power button for ten seconds until the indicator blinks amber, then release. The device restores factory settings, reboots twice, and broadcasts a setup network named after its serial number. Connect to that network and open the configuration page at the default gateway address.",
    },
    {
      id: "en-07",
      textClass: "english",
      role: "calibration",
      text: "A byte-pair encoder builds its vocabulary by repeatedly merging the most frequent adjacent symbol pair in a training corpus. At inference time the merges are replayed in rank order, so the same text always produces the same token sequence — determinism is what makes offline counting possible at all.",
    },
    {
      id: "en-08",
      textClass: "english",
      role: "holdout",
      text: "Thanks for the quick turnaround! Two small things before we ship: the header still says 2025 in the footer copyright, and the pricing table overflows on narrow screens. Otherwise looks great — approve from my side once those are fixed.",
    },
    {
      id: "en-09",
      textClass: "english",
      role: "calibration",
      text: "The committee reviewed the proposal in light of the applicable procurement regulations, noting that the threshold for competitive tendering had been exceeded and that, consequently, a direct award would require a documented exemption signed by the accounting officer and retained for a minimum of seven years.",
    },
    {
      id: "en-10",
      textClass: "english",
      role: "holdout",
      text: "Migration checklist: freeze writes on the old cluster, take a final snapshot, replay the write-ahead log up to the freeze point, flip the DNS record with a 60-second TTL, watch error rates for fifteen minutes, then decommission the old primary. Roll back by reversing the DNS flip; the snapshot stays valid for 24 hours.",
    },
    {
      id: "ja-01",
      textClass: "japanese",
      role: "calibration",
      text: "トークン数の把握は、API呼び出しの費用を呼び出す前に見積もるための前提である。利用者ごとの使用量を集計する仕組みは、トークンを数えられなければ成立しない。",
    },
    {
      id: "ja-02",
      textClass: "japanese",
      role: "holdout",
      text: "請求書の締め日は毎月末日、支払期日は翌月末日とする。振込手数料は支払側の負担とし、期日までに入金が確認できない場合は、担当者へ連絡のうえ翌営業日までに対応を協議する。",
    },
    {
      id: "ja-03",
      textClass: "japanese",
      role: "calibration",
      text: "夕方の商店街は買い物客でにぎわっていた。八百屋の店先には秋の野菜が並び、隣の魚屋からは威勢のいい呼び込みの声が聞こえる。子どもたちが路地を駆け抜け、自転車のベルが鳴った。",
    },
    {
      id: "ja-04",
      textClass: "japanese",
      role: "holdout",
      text: "本機能を利用するには、管理画面で二段階認証を有効にしてください。設定後、登録済みのメールアドレスに確認コードが送信されます。コードの有効期限は10分間です。期限切れの場合は再送信ボタンから新しいコードを取得してください。なお、五回連続で誤ったコードを入力するとアカウントは一時的にロックされます。",
    },
    {
      id: "ja-05",
      textClass: "japanese",
      role: "calibration",
      text: "御社ますますご清栄のこととお慶び申し上げます。さて、先日ご依頼いただきました見積書を添付のとおりお送りいたします。ご不明な点がございましたら、担当までお気軽にお問い合わせください。今後ともよろしくお願い申し上げます。",
    },
    {
      id: "ja-06",
      textClass: "japanese",
      role: "holdout",
      text: "会議は10時に始まった。議題は三つ。第一に来期の予算配分、第二に新製品の発売時期、第三に採用計画である。予算については営業部と開発部の要求が重なり、結論は持ち越しとなった。",
    },
    {
      id: "ja-07",
      textClass: "japanese",
      role: "calibration",
      text: "日本語のテキストは、英語に比べて1文字あたりのトークン数が多くなる傾向がある。語彙に含まれない漢字はバイト単位に分解されるため、同じ意味内容でも課金対象のトークン数は増える。この特性は、多言語プロダクトの費用見積もりで無視できない差になる。",
    },
    {
      id: "ja-08",
      textClass: "japanese",
      role: "holdout",
      text: "新幹線は定刻に東京駅を出発した。窓側の席に座り、弁当を広げる。富士山が見えるのは静岡を過ぎたあたりだと隣の乗客が教えてくれた。あいにくの曇り空だったが、名古屋に着くころには日が差し始めた。",
    },
    {
      id: "ja-09",
      textClass: "japanese",
      role: "calibration",
      text: "障害発生時は、まず影響範囲を特定し、次に一次対応として該当サービスを縮退運転へ切り替える。復旧後は時系列で経緯を整理し、再発防止策とあわせて障害報告書を三営業日以内に提出すること。",
    },
    {
      id: "ja-10",
      textClass: "japanese",
      role: "holdout",
      text: "春の展示会への出展が決まりました。ブースの位置は入口から二列目、小間番号はB-12です。設営は前日の午後3時から可能で、搬入口は建物北側にあります。当日はスタッフ4名体制で、交代で休憩を取りながら対応します。パンフレットは800部、ノベルティは500個を用意する予定です。",
    },
    {
      id: "code-01",
      textClass: "code",
      role: "calibration",
      text: 'export const meter = (usage: Usage): Cost => {\n  const input = usage.inputTokens * PRICE.input;\n  const output = usage.outputTokens * PRICE.output;\n  return { total: input + output, currency: "USD" };\n};\n',
    },
    {
      id: "code-02",
      textClass: "code",
      role: "holdout",
      text: 'def count_tokens(text: str, vocab: dict[bytes, int]) -> int:\n    parts = [bytes([b]) for b in text.encode("utf-8")]\n    while True:\n        best = None\n        for i in range(len(parts) - 1):\n            rank = vocab.get(parts[i] + parts[i + 1])\n            if rank is not None and (best is None or rank < best[1]):\n                best = (i, rank)\n        if best is None:\n            return len(parts)\n        i = best[0]\n        parts[i : i + 2] = [parts[i] + parts[i + 1]]\n',
    },
    {
      id: "code-03",
      textClass: "code",
      role: "calibration",
      text: '{\n  "model": "gpt-5.5",\n  "messages": [{ "role": "user", "content": "Hello" }],\n  "max_completion_tokens": 16,\n  "temperature": 0,\n  "stream": false\n}\n',
    },
    {
      id: "code-04",
      textClass: "code",
      role: "holdout",
      text: "SELECT principal_id,\n       SUM(input_tokens)  AS input_tokens,\n       SUM(output_tokens) AS output_tokens,\n       SUM(cost_usd)      AS cost_usd\nFROM usage_records\nWHERE recorded_at >= date_trunc('month', now())\nGROUP BY principal_id\nORDER BY cost_usd DESC\nLIMIT 20;\n",
    },
    {
      id: "code-05",
      textClass: "code",
      role: "calibration",
      text: '#!/usr/bin/env bash\nset -euo pipefail\n\nfor topic in $(node ./list-topics.js); do\n  echo "==> ${topic}"\n  npm run research -- "${topic}" --fixture\ndone\n\ngit diff --exit-code -- docs/\n',
    },
    {
      id: "code-06",
      textClass: "code",
      role: "holdout",
      text: 'type Brand<T, B extends string> = T & { readonly __brand: B };\ntype TokenCount = Brand<number, "TokenCount">;\ntype UsdAmount = Brand<number, "UsdAmount">;\n\nconst tokenCount = (n: number): TokenCount => {\n  if (!Number.isInteger(n) || n < 0) throw new Error("invalid token count");\n  return n as TokenCount;\n};\n',
    },
    {
      id: "code-07",
      textClass: "code",
      role: "calibration",
      text: 'func (m *Meter) Record(ctx context.Context, r UsageRecord) error {\n\tif r.PrincipalID == "" {\n\t\treturn ErrMissingPrincipal\n\t}\n\tm.mu.Lock()\n\tdefer m.mu.Unlock()\n\tm.totals[r.PrincipalID] += r.InputTokens + r.OutputTokens\n\treturn m.store.Append(ctx, r)\n}\n',
    },
    {
      id: "code-08",
      textClass: "code",
      role: "holdout",
      text: '<form method="post" action="/api/quota">\n  <label for="ceiling">Monthly ceiling (USD)</label>\n  <input id="ceiling" name="ceiling" type="number" min="0" step="0.01" required />\n  <button type="submit">Save</button>\n</form>\n<style>\n  form { display: grid; gap: 0.5rem; max-width: 20rem; }\n</style>\n',
    },
    {
      id: "code-09",
      textClass: "code",
      role: "calibration",
      text: "# Usage metering configuration\nmetering:\n  enabled: true\n  aggregation_window: 1h\n  attribution: principal\n  export:\n    format: openmetrics\n    endpoint: /metrics\n  retention:\n    raw_records_days: 90\n    aggregates_days: 730\n",
    },
    {
      id: "code-10",
      textClass: "code",
      role: "holdout",
      text: 'import { describe, expect, it } from "vitest";\nimport { estimateCost } from "./cost";\n\ndescribe("estimateCost", () => {\n  it("prices input and output tokens separately", () => {\n    const cost = estimateCost({ inputTokens: 1000, outputTokens: 200 });\n    expect(cost.inputUsd).toBeCloseTo(0.003);\n    expect(cost.outputUsd).toBeCloseTo(0.003);\n  });\n});\n',
    },
  ];

export type ArticleRow = Readonly<{
  sampleId: string;
  textClass: TextClass;
  role: "calibration" | "holdout";
  /** The article's recorded character count for the sample. */
  chars: number;
  /** The article's recorded UTF-8 byte count for the sample. */
  utf8Bytes: number;
  /** The provider's API-reported token count — the ground truth. */
  apiTokens: number;
  /** The self-count's prediction of apiTokens, as the article recorded it. */
  predictedTokens: number;
  /** The exact self-BPE content count (exact families only). */
  selfContentTokens: number | undefined;
  /** 100 x (predicted - api) / api, as the article recorded it. */
  errorPct: number;
}>;

export type ArticleFamily = Readonly<{
  familyId: string;
  apiModelId: string;
  countingMethod: string;
  holdoutMeanAbsErrorPct: number;
  holdoutMaxAbsErrorPct: number;
  withinTarget: boolean;
  rows: ReadonlyArray<ArticleRow>;
}>;

/**
 * Every family's measured rows, exactly as published.
 */
export const FAMILIES: ReadonlyArray<ArticleFamily> =
  [
    {
      familyId: "anthropic-claude",
      apiModelId: "claude-sonnet-5",
      countingMethod: "calibrated-estimator",
      holdoutMeanAbsErrorPct: 8.54,
      holdoutMaxAbsErrorPct: 16.24,
      withinTarget: false,
      rows: [
        {
          sampleId: "en-01",
          textClass: "english",
          role: "calibration",
          chars: 167,
          utf8Bytes: 167,
          apiTokens: 54,
          predictedTokens: 58,
          selfContentTokens: undefined,
          errorPct: 7.41,
        },
        {
          sampleId: "en-02",
          textClass: "english",
          role: "holdout",
          chars: 236,
          utf8Bytes: 236,
          apiTokens: 71,
          predictedTokens: 80,
          selfContentTokens: undefined,
          errorPct: 12.68,
        },
        {
          sampleId: "en-03",
          textClass: "english",
          role: "calibration",
          chars: 271,
          utf8Bytes: 271,
          apiTokens: 89,
          predictedTokens: 92,
          selfContentTokens: undefined,
          errorPct: 3.37,
        },
        {
          sampleId: "en-04",
          textClass: "english",
          role: "holdout",
          chars: 363,
          utf8Bytes: 365,
          apiTokens: 128,
          predictedTokens: 122,
          selfContentTokens: undefined,
          errorPct: -4.69,
        },
        {
          sampleId: "en-05",
          textClass: "english",
          role: "calibration",
          chars: 259,
          utf8Bytes: 259,
          apiTokens: 113,
          predictedTokens: 88,
          selfContentTokens: undefined,
          errorPct: -22.12,
        },
        {
          sampleId: "en-06",
          textClass: "english",
          role: "holdout",
          chars: 309,
          utf8Bytes: 309,
          apiTokens: 90,
          predictedTokens: 104,
          selfContentTokens: undefined,
          errorPct: 15.56,
        },
        {
          sampleId: "en-07",
          textClass: "english",
          role: "calibration",
          chars: 300,
          utf8Bytes: 302,
          apiTokens: 98,
          predictedTokens: 101,
          selfContentTokens: undefined,
          errorPct: 3.06,
        },
        {
          sampleId: "en-08",
          textClass: "english",
          role: "holdout",
          chars: 235,
          utf8Bytes: 237,
          apiTokens: 81,
          predictedTokens: 80,
          selfContentTokens: undefined,
          errorPct: -1.23,
        },
        {
          sampleId: "en-09",
          textClass: "english",
          role: "calibration",
          chars: 309,
          utf8Bytes: 309,
          apiTokens: 92,
          predictedTokens: 104,
          selfContentTokens: undefined,
          errorPct: 13.04,
        },
        {
          sampleId: "en-10",
          textClass: "english",
          role: "holdout",
          chars: 320,
          utf8Bytes: 320,
          apiTokens: 121,
          predictedTokens: 108,
          selfContentTokens: undefined,
          errorPct: -10.74,
        },
        {
          sampleId: "ja-01",
          textClass: "japanese",
          role: "calibration",
          chars: 78,
          utf8Bytes: 228,
          apiTokens: 76,
          predictedTokens: 80,
          selfContentTokens: undefined,
          errorPct: 5.26,
        },
        {
          sampleId: "ja-02",
          textClass: "japanese",
          role: "holdout",
          chars: 83,
          utf8Bytes: 249,
          apiTokens: 89,
          predictedTokens: 85,
          selfContentTokens: undefined,
          errorPct: -4.49,
        },
        {
          sampleId: "ja-03",
          textClass: "japanese",
          role: "calibration",
          chars: 85,
          utf8Bytes: 255,
          apiTokens: 102,
          predictedTokens: 87,
          selfContentTokens: undefined,
          errorPct: -14.71,
        },
        {
          sampleId: "ja-04",
          textClass: "japanese",
          role: "holdout",
          chars: 148,
          utf8Bytes: 440,
          apiTokens: 132,
          predictedTokens: 149,
          selfContentTokens: undefined,
          errorPct: 12.88,
        },
        {
          sampleId: "ja-05",
          textClass: "japanese",
          role: "calibration",
          chars: 108,
          utf8Bytes: 324,
          apiTokens: 104,
          predictedTokens: 110,
          selfContentTokens: undefined,
          errorPct: 5.77,
        },
        {
          sampleId: "ja-06",
          textClass: "japanese",
          role: "holdout",
          chars: 86,
          utf8Bytes: 254,
          apiTokens: 85,
          predictedTokens: 88,
          selfContentTokens: undefined,
          errorPct: 3.53,
        },
        {
          sampleId: "ja-07",
          textClass: "japanese",
          role: "calibration",
          chars: 120,
          utf8Bytes: 358,
          apiTokens: 118,
          predictedTokens: 121,
          selfContentTokens: undefined,
          errorPct: 2.54,
        },
        {
          sampleId: "ja-08",
          textClass: "japanese",
          role: "holdout",
          chars: 94,
          utf8Bytes: 282,
          apiTokens: 108,
          predictedTokens: 96,
          selfContentTokens: undefined,
          errorPct: -11.11,
        },
        {
          sampleId: "ja-09",
          textClass: "japanese",
          role: "calibration",
          chars: 90,
          utf8Bytes: 270,
          apiTokens: 95,
          predictedTokens: 92,
          selfContentTokens: undefined,
          errorPct: -3.16,
        },
        {
          sampleId: "ja-10",
          textClass: "japanese",
          role: "holdout",
          chars: 136,
          utf8Bytes: 384,
          apiTokens: 126,
          predictedTokens: 137,
          selfContentTokens: undefined,
          errorPct: 8.73,
        },
        {
          sampleId: "code-01",
          textClass: "code",
          role: "calibration",
          chars: 204,
          utf8Bytes: 204,
          apiTokens: 86,
          predictedTokens: 100,
          selfContentTokens: undefined,
          errorPct: 16.28,
        },
        {
          sampleId: "code-02",
          textClass: "code",
          role: "holdout",
          chars: 477,
          utf8Bytes: 477,
          apiTokens: 197,
          predictedTokens: 229,
          selfContentTokens: undefined,
          errorPct: 16.24,
        },
        {
          sampleId: "code-03",
          textClass: "code",
          role: "calibration",
          chars: 151,
          utf8Bytes: 151,
          apiTokens: 80,
          predictedTokens: 75,
          selfContentTokens: undefined,
          errorPct: -6.25,
        },
        {
          sampleId: "code-04",
          textClass: "code",
          role: "holdout",
          chars: 268,
          utf8Bytes: 268,
          apiTokens: 141,
          predictedTokens: 130,
          selfContentTokens: undefined,
          errorPct: -7.8,
        },
        {
          sampleId: "code-05",
          textClass: "code",
          role: "calibration",
          chars: 182,
          utf8Bytes: 182,
          apiTokens: 92,
          predictedTokens: 90,
          selfContentTokens: undefined,
          errorPct: -2.17,
        },
        {
          sampleId: "code-06",
          textClass: "code",
          role: "holdout",
          chars: 310,
          utf8Bytes: 310,
          apiTokens: 143,
          predictedTokens: 150,
          selfContentTokens: undefined,
          errorPct: 4.9,
        },
        {
          sampleId: "code-07",
          textClass: "code",
          role: "calibration",
          chars: 251,
          utf8Bytes: 251,
          apiTokens: 143,
          predictedTokens: 122,
          selfContentTokens: undefined,
          errorPct: -14.69,
        },
        {
          sampleId: "code-08",
          textClass: "code",
          role: "holdout",
          chars: 297,
          utf8Bytes: 297,
          apiTokens: 135,
          predictedTokens: 144,
          selfContentTokens: undefined,
          errorPct: 6.67,
        },
        {
          sampleId: "code-09",
          textClass: "code",
          role: "calibration",
          chars: 227,
          utf8Bytes: 227,
          apiTokens: 97,
          predictedTokens: 111,
          selfContentTokens: undefined,
          errorPct: 14.43,
        },
        {
          sampleId: "code-10",
          textClass: "code",
          role: "holdout",
          chars: 354,
          utf8Bytes: 354,
          apiTokens: 160,
          predictedTokens: 171,
          selfContentTokens: undefined,
          errorPct: 6.88,
        },
      ],
    },
    {
      familyId: "openai-gpt",
      apiModelId: "gpt-5.5",
      countingMethod: "exact-bpe",
      holdoutMeanAbsErrorPct: 0,
      holdoutMaxAbsErrorPct: 0,
      withinTarget: true,
      rows: [
        {
          sampleId: "en-01",
          textClass: "english",
          role: "calibration",
          chars: 167,
          utf8Bytes: 167,
          apiTokens: 38,
          predictedTokens: 38,
          selfContentTokens: 32,
          errorPct: 0,
        },
        {
          sampleId: "en-02",
          textClass: "english",
          role: "holdout",
          chars: 236,
          utf8Bytes: 236,
          apiTokens: 50,
          predictedTokens: 50,
          selfContentTokens: 44,
          errorPct: 0,
        },
        {
          sampleId: "en-03",
          textClass: "english",
          role: "calibration",
          chars: 271,
          utf8Bytes: 271,
          apiTokens: 59,
          predictedTokens: 59,
          selfContentTokens: 53,
          errorPct: 0,
        },
        {
          sampleId: "en-04",
          textClass: "english",
          role: "holdout",
          chars: 363,
          utf8Bytes: 365,
          apiTokens: 80,
          predictedTokens: 80,
          selfContentTokens: 74,
          errorPct: 0,
        },
        {
          sampleId: "en-05",
          textClass: "english",
          role: "calibration",
          chars: 259,
          utf8Bytes: 259,
          apiTokens: 72,
          predictedTokens: 72,
          selfContentTokens: 66,
          errorPct: 0,
        },
        {
          sampleId: "en-06",
          textClass: "english",
          role: "holdout",
          chars: 309,
          utf8Bytes: 309,
          apiTokens: 64,
          predictedTokens: 64,
          selfContentTokens: 58,
          errorPct: 0,
        },
        {
          sampleId: "en-07",
          textClass: "english",
          role: "calibration",
          chars: 300,
          utf8Bytes: 302,
          apiTokens: 62,
          predictedTokens: 62,
          selfContentTokens: 56,
          errorPct: 0,
        },
        {
          sampleId: "en-08",
          textClass: "english",
          role: "holdout",
          chars: 235,
          utf8Bytes: 237,
          apiTokens: 54,
          predictedTokens: 54,
          selfContentTokens: 48,
          errorPct: 0,
        },
        {
          sampleId: "en-09",
          textClass: "english",
          role: "calibration",
          chars: 309,
          utf8Bytes: 309,
          apiTokens: 57,
          predictedTokens: 57,
          selfContentTokens: 51,
          errorPct: 0,
        },
        {
          sampleId: "en-10",
          textClass: "english",
          role: "holdout",
          chars: 320,
          utf8Bytes: 320,
          apiTokens: 75,
          predictedTokens: 75,
          selfContentTokens: 69,
          errorPct: 0,
        },
        {
          sampleId: "ja-01",
          textClass: "japanese",
          role: "calibration",
          chars: 78,
          utf8Bytes: 228,
          apiTokens: 71,
          predictedTokens: 71,
          selfContentTokens: 65,
          errorPct: 0,
        },
        {
          sampleId: "ja-02",
          textClass: "japanese",
          role: "holdout",
          chars: 83,
          utf8Bytes: 249,
          apiTokens: 76,
          predictedTokens: 76,
          selfContentTokens: 70,
          errorPct: 0,
        },
        {
          sampleId: "ja-03",
          textClass: "japanese",
          role: "calibration",
          chars: 85,
          utf8Bytes: 255,
          apiTokens: 84,
          predictedTokens: 84,
          selfContentTokens: 78,
          errorPct: 0,
        },
        {
          sampleId: "ja-04",
          textClass: "japanese",
          role: "holdout",
          chars: 148,
          utf8Bytes: 440,
          apiTokens: 106,
          predictedTokens: 106,
          selfContentTokens: 100,
          errorPct: 0,
        },
        {
          sampleId: "ja-05",
          textClass: "japanese",
          role: "calibration",
          chars: 108,
          utf8Bytes: 324,
          apiTokens: 78,
          predictedTokens: 78,
          selfContentTokens: 72,
          errorPct: 0,
        },
        {
          sampleId: "ja-06",
          textClass: "japanese",
          role: "holdout",
          chars: 86,
          utf8Bytes: 254,
          apiTokens: 78,
          predictedTokens: 78,
          selfContentTokens: 72,
          errorPct: 0,
        },
        {
          sampleId: "ja-07",
          textClass: "japanese",
          role: "calibration",
          chars: 120,
          utf8Bytes: 358,
          apiTokens: 102,
          predictedTokens: 102,
          selfContentTokens: 96,
          errorPct: 0,
        },
        {
          sampleId: "ja-08",
          textClass: "japanese",
          role: "holdout",
          chars: 94,
          utf8Bytes: 282,
          apiTokens: 96,
          predictedTokens: 96,
          selfContentTokens: 90,
          errorPct: 0,
        },
        {
          sampleId: "ja-09",
          textClass: "japanese",
          role: "calibration",
          chars: 90,
          utf8Bytes: 270,
          apiTokens: 82,
          predictedTokens: 82,
          selfContentTokens: 76,
          errorPct: 0,
        },
        {
          sampleId: "ja-10",
          textClass: "japanese",
          role: "holdout",
          chars: 136,
          utf8Bytes: 384,
          apiTokens: 100,
          predictedTokens: 100,
          selfContentTokens: 94,
          errorPct: 0,
        },
        {
          sampleId: "code-01",
          textClass: "code",
          role: "calibration",
          chars: 204,
          utf8Bytes: 204,
          apiTokens: 56,
          predictedTokens: 56,
          selfContentTokens: 50,
          errorPct: 0,
        },
        {
          sampleId: "code-02",
          textClass: "code",
          role: "holdout",
          chars: 477,
          utf8Bytes: 477,
          apiTokens: 143,
          predictedTokens: 143,
          selfContentTokens: 137,
          errorPct: 0,
        },
        {
          sampleId: "code-03",
          textClass: "code",
          role: "calibration",
          chars: 151,
          utf8Bytes: 151,
          apiTokens: 60,
          predictedTokens: 60,
          selfContentTokens: 54,
          errorPct: 0,
        },
        {
          sampleId: "code-04",
          textClass: "code",
          role: "holdout",
          chars: 268,
          utf8Bytes: 268,
          apiTokens: 73,
          predictedTokens: 73,
          selfContentTokens: 67,
          errorPct: 0,
        },
        {
          sampleId: "code-05",
          textClass: "code",
          role: "calibration",
          chars: 182,
          utf8Bytes: 182,
          apiTokens: 61,
          predictedTokens: 61,
          selfContentTokens: 55,
          errorPct: 0,
        },
        {
          sampleId: "code-06",
          textClass: "code",
          role: "holdout",
          chars: 310,
          utf8Bytes: 310,
          apiTokens: 92,
          predictedTokens: 92,
          selfContentTokens: 86,
          errorPct: 0,
        },
        {
          sampleId: "code-07",
          textClass: "code",
          role: "calibration",
          chars: 251,
          utf8Bytes: 251,
          apiTokens: 75,
          predictedTokens: 75,
          selfContentTokens: 69,
          errorPct: 0,
        },
        {
          sampleId: "code-08",
          textClass: "code",
          role: "holdout",
          chars: 297,
          utf8Bytes: 297,
          apiTokens: 103,
          predictedTokens: 103,
          selfContentTokens: 97,
          errorPct: 0,
        },
        {
          sampleId: "code-09",
          textClass: "code",
          role: "calibration",
          chars: 227,
          utf8Bytes: 227,
          apiTokens: 66,
          predictedTokens: 66,
          selfContentTokens: 60,
          errorPct: 0,
        },
        {
          sampleId: "code-10",
          textClass: "code",
          role: "holdout",
          chars: 354,
          utf8Bytes: 354,
          apiTokens: 102,
          predictedTokens: 102,
          selfContentTokens: 96,
          errorPct: 0,
        },
      ],
    },
    {
      familyId: "google-gemini",
      apiModelId: "gemini-3.1-pro-preview",
      countingMethod: "calibrated-estimator",
      holdoutMeanAbsErrorPct: 6.6,
      holdoutMaxAbsErrorPct: 15.73,
      withinTarget: false,
      rows: [
        {
          sampleId: "en-01",
          textClass: "english",
          role: "calibration",
          chars: 167,
          utf8Bytes: 167,
          apiTokens: 32,
          predictedTokens: 37,
          selfContentTokens: undefined,
          errorPct: 15.63,
        },
        {
          sampleId: "en-02",
          textClass: "english",
          role: "holdout",
          chars: 236,
          utf8Bytes: 236,
          apiTokens: 45,
          predictedTokens: 49,
          selfContentTokens: undefined,
          errorPct: 8.89,
        },
        {
          sampleId: "en-03",
          textClass: "english",
          role: "calibration",
          chars: 271,
          utf8Bytes: 271,
          apiTokens: 55,
          predictedTokens: 55,
          selfContentTokens: undefined,
          errorPct: 0,
        },
        {
          sampleId: "en-04",
          textClass: "english",
          role: "holdout",
          chars: 363,
          utf8Bytes: 365,
          apiTokens: 74,
          predictedTokens: 72,
          selfContentTokens: undefined,
          errorPct: -2.7,
        },
        {
          sampleId: "en-05",
          textClass: "english",
          role: "calibration",
          chars: 259,
          utf8Bytes: 259,
          apiTokens: 72,
          predictedTokens: 53,
          selfContentTokens: undefined,
          errorPct: -26.39,
        },
        {
          sampleId: "en-06",
          textClass: "english",
          role: "holdout",
          chars: 309,
          utf8Bytes: 309,
          apiTokens: 59,
          predictedTokens: 62,
          selfContentTokens: undefined,
          errorPct: 5.08,
        },
        {
          sampleId: "en-07",
          textClass: "english",
          role: "calibration",
          chars: 300,
          utf8Bytes: 302,
          apiTokens: 57,
          predictedTokens: 60,
          selfContentTokens: undefined,
          errorPct: 5.26,
        },
        {
          sampleId: "en-08",
          textClass: "english",
          role: "holdout",
          chars: 235,
          utf8Bytes: 237,
          apiTokens: 50,
          predictedTokens: 49,
          selfContentTokens: undefined,
          errorPct: -2,
        },
        {
          sampleId: "en-09",
          textClass: "english",
          role: "calibration",
          chars: 309,
          utf8Bytes: 309,
          apiTokens: 52,
          predictedTokens: 62,
          selfContentTokens: undefined,
          errorPct: 19.23,
        },
        {
          sampleId: "en-10",
          textClass: "english",
          role: "holdout",
          chars: 320,
          utf8Bytes: 320,
          apiTokens: 72,
          predictedTokens: 64,
          selfContentTokens: undefined,
          errorPct: -11.11,
        },
        {
          sampleId: "ja-01",
          textClass: "japanese",
          role: "calibration",
          chars: 78,
          utf8Bytes: 228,
          apiTokens: 44,
          predictedTokens: 46,
          selfContentTokens: undefined,
          errorPct: 4.55,
        },
        {
          sampleId: "ja-02",
          textClass: "japanese",
          role: "holdout",
          chars: 83,
          utf8Bytes: 249,
          apiTokens: 50,
          predictedTokens: 49,
          selfContentTokens: undefined,
          errorPct: -2,
        },
        {
          sampleId: "ja-03",
          textClass: "japanese",
          role: "calibration",
          chars: 85,
          utf8Bytes: 255,
          apiTokens: 58,
          predictedTokens: 50,
          selfContentTokens: undefined,
          errorPct: -13.79,
        },
        {
          sampleId: "ja-04",
          textClass: "japanese",
          role: "holdout",
          chars: 148,
          utf8Bytes: 440,
          apiTokens: 73,
          predictedTokens: 81,
          selfContentTokens: undefined,
          errorPct: 10.96,
        },
        {
          sampleId: "ja-05",
          textClass: "japanese",
          role: "calibration",
          chars: 108,
          utf8Bytes: 324,
          apiTokens: 53,
          predictedTokens: 61,
          selfContentTokens: undefined,
          errorPct: 15.09,
        },
        {
          sampleId: "ja-06",
          textClass: "japanese",
          role: "holdout",
          chars: 86,
          utf8Bytes: 254,
          apiTokens: 52,
          predictedTokens: 50,
          selfContentTokens: undefined,
          errorPct: -3.85,
        },
        {
          sampleId: "ja-07",
          textClass: "japanese",
          role: "calibration",
          chars: 120,
          utf8Bytes: 358,
          apiTokens: 66,
          predictedTokens: 67,
          selfContentTokens: undefined,
          errorPct: 1.52,
        },
        {
          sampleId: "ja-08",
          textClass: "japanese",
          role: "holdout",
          chars: 94,
          utf8Bytes: 282,
          apiTokens: 63,
          predictedTokens: 54,
          selfContentTokens: undefined,
          errorPct: -14.29,
        },
        {
          sampleId: "ja-09",
          textClass: "japanese",
          role: "calibration",
          chars: 90,
          utf8Bytes: 270,
          apiTokens: 57,
          predictedTokens: 52,
          selfContentTokens: undefined,
          errorPct: -8.77,
        },
        {
          sampleId: "ja-10",
          textClass: "japanese",
          role: "holdout",
          chars: 136,
          utf8Bytes: 384,
          apiTokens: 89,
          predictedTokens: 75,
          selfContentTokens: undefined,
          errorPct: -15.73,
        },
        {
          sampleId: "code-01",
          textClass: "code",
          role: "calibration",
          chars: 204,
          utf8Bytes: 204,
          apiTokens: 60,
          predictedTokens: 70,
          selfContentTokens: undefined,
          errorPct: 16.67,
        },
        {
          sampleId: "code-02",
          textClass: "code",
          role: "holdout",
          chars: 477,
          utf8Bytes: 477,
          apiTokens: 162,
          predictedTokens: 155,
          selfContentTokens: undefined,
          errorPct: -4.32,
        },
        {
          sampleId: "code-03",
          textClass: "code",
          role: "calibration",
          chars: 151,
          utf8Bytes: 151,
          apiTokens: 63,
          predictedTokens: 54,
          selfContentTokens: undefined,
          errorPct: -14.29,
        },
        {
          sampleId: "code-04",
          textClass: "code",
          role: "holdout",
          chars: 268,
          utf8Bytes: 268,
          apiTokens: 85,
          predictedTokens: 90,
          selfContentTokens: undefined,
          errorPct: 5.88,
        },
        {
          sampleId: "code-05",
          textClass: "code",
          role: "calibration",
          chars: 182,
          utf8Bytes: 182,
          apiTokens: 62,
          predictedTokens: 63,
          selfContentTokens: undefined,
          errorPct: 1.61,
        },
        {
          sampleId: "code-06",
          textClass: "code",
          role: "holdout",
          chars: 310,
          utf8Bytes: 310,
          apiTokens: 100,
          predictedTokens: 103,
          selfContentTokens: undefined,
          errorPct: 3,
        },
        {
          sampleId: "code-07",
          textClass: "code",
          role: "calibration",
          chars: 251,
          utf8Bytes: 251,
          apiTokens: 93,
          predictedTokens: 85,
          selfContentTokens: undefined,
          errorPct: -8.6,
        },
        {
          sampleId: "code-08",
          textClass: "code",
          role: "holdout",
          chars: 297,
          utf8Bytes: 297,
          apiTokens: 108,
          predictedTokens: 99,
          selfContentTokens: undefined,
          errorPct: -8.33,
        },
        {
          sampleId: "code-09",
          textClass: "code",
          role: "calibration",
          chars: 227,
          utf8Bytes: 227,
          apiTokens: 72,
          predictedTokens: 77,
          selfContentTokens: undefined,
          errorPct: 6.94,
        },
        {
          sampleId: "code-10",
          textClass: "code",
          role: "holdout",
          chars: 354,
          utf8Bytes: 354,
          apiTokens: 118,
          predictedTokens: 117,
          selfContentTokens: undefined,
          errorPct: -0.85,
        },
      ],
    },
    {
      familyId: "oss-qwen",
      apiModelId:
        "@cf/qwen/qwen2.5-coder-32b-instruct",
      countingMethod: "exact-bpe",
      holdoutMeanAbsErrorPct: 0,
      holdoutMaxAbsErrorPct: 0,
      withinTarget: true,
      rows: [
        {
          sampleId: "en-01",
          textClass: "english",
          role: "calibration",
          chars: 167,
          utf8Bytes: 167,
          apiTokens: 61,
          predictedTokens: 61,
          selfContentTokens: 32,
          errorPct: 0,
        },
        {
          sampleId: "en-02",
          textClass: "english",
          role: "holdout",
          chars: 236,
          utf8Bytes: 236,
          apiTokens: 73,
          predictedTokens: 73,
          selfContentTokens: 44,
          errorPct: 0,
        },
        {
          sampleId: "en-03",
          textClass: "english",
          role: "calibration",
          chars: 271,
          utf8Bytes: 271,
          apiTokens: 84,
          predictedTokens: 84,
          selfContentTokens: 55,
          errorPct: 0,
        },
        {
          sampleId: "en-04",
          textClass: "english",
          role: "holdout",
          chars: 363,
          utf8Bytes: 365,
          apiTokens: 104,
          predictedTokens: 104,
          selfContentTokens: 75,
          errorPct: 0,
        },
        {
          sampleId: "en-05",
          textClass: "english",
          role: "calibration",
          chars: 259,
          utf8Bytes: 259,
          apiTokens: 101,
          predictedTokens: 101,
          selfContentTokens: 72,
          errorPct: 0,
        },
        {
          sampleId: "en-06",
          textClass: "english",
          role: "holdout",
          chars: 309,
          utf8Bytes: 309,
          apiTokens: 88,
          predictedTokens: 88,
          selfContentTokens: 59,
          errorPct: 0,
        },
        {
          sampleId: "en-07",
          textClass: "english",
          role: "calibration",
          chars: 300,
          utf8Bytes: 302,
          apiTokens: 85,
          predictedTokens: 85,
          selfContentTokens: 56,
          errorPct: 0,
        },
        {
          sampleId: "en-08",
          textClass: "english",
          role: "holdout",
          chars: 235,
          utf8Bytes: 237,
          apiTokens: 79,
          predictedTokens: 79,
          selfContentTokens: 50,
          errorPct: 0,
        },
        {
          sampleId: "en-09",
          textClass: "english",
          role: "calibration",
          chars: 309,
          utf8Bytes: 309,
          apiTokens: 80,
          predictedTokens: 80,
          selfContentTokens: 51,
          errorPct: 0,
        },
        {
          sampleId: "en-10",
          textClass: "english",
          role: "holdout",
          chars: 320,
          utf8Bytes: 320,
          apiTokens: 99,
          predictedTokens: 99,
          selfContentTokens: 70,
          errorPct: 0,
        },
        {
          sampleId: "ja-01",
          textClass: "japanese",
          role: "calibration",
          chars: 78,
          utf8Bytes: 228,
          apiTokens: 79,
          predictedTokens: 79,
          selfContentTokens: 50,
          errorPct: 0,
        },
        {
          sampleId: "ja-02",
          textClass: "japanese",
          role: "holdout",
          chars: 83,
          utf8Bytes: 249,
          apiTokens: 99,
          predictedTokens: 99,
          selfContentTokens: 70,
          errorPct: 0,
        },
        {
          sampleId: "ja-03",
          textClass: "japanese",
          role: "calibration",
          chars: 85,
          utf8Bytes: 255,
          apiTokens: 99,
          predictedTokens: 99,
          selfContentTokens: 70,
          errorPct: 0,
        },
        {
          sampleId: "ja-04",
          textClass: "japanese",
          role: "holdout",
          chars: 148,
          utf8Bytes: 440,
          apiTokens: 126,
          predictedTokens: 126,
          selfContentTokens: 97,
          errorPct: 0,
        },
        {
          sampleId: "ja-05",
          textClass: "japanese",
          role: "calibration",
          chars: 108,
          utf8Bytes: 324,
          apiTokens: 96,
          predictedTokens: 96,
          selfContentTokens: 67,
          errorPct: 0,
        },
        {
          sampleId: "ja-06",
          textClass: "japanese",
          role: "holdout",
          chars: 86,
          utf8Bytes: 254,
          apiTokens: 98,
          predictedTokens: 98,
          selfContentTokens: 69,
          errorPct: 0,
        },
        {
          sampleId: "ja-07",
          textClass: "japanese",
          role: "calibration",
          chars: 120,
          utf8Bytes: 358,
          apiTokens: 113,
          predictedTokens: 113,
          selfContentTokens: 84,
          errorPct: 0,
        },
        {
          sampleId: "ja-08",
          textClass: "japanese",
          role: "holdout",
          chars: 94,
          utf8Bytes: 282,
          apiTokens: 111,
          predictedTokens: 111,
          selfContentTokens: 82,
          errorPct: 0,
        },
        {
          sampleId: "ja-09",
          textClass: "japanese",
          role: "calibration",
          chars: 90,
          utf8Bytes: 270,
          apiTokens: 106,
          predictedTokens: 106,
          selfContentTokens: 77,
          errorPct: 0,
        },
        {
          sampleId: "ja-10",
          textClass: "japanese",
          role: "holdout",
          chars: 136,
          utf8Bytes: 384,
          apiTokens: 132,
          predictedTokens: 132,
          selfContentTokens: 103,
          errorPct: 0,
        },
        {
          sampleId: "code-01",
          textClass: "code",
          role: "calibration",
          chars: 204,
          utf8Bytes: 204,
          apiTokens: 79,
          predictedTokens: 79,
          selfContentTokens: 50,
          errorPct: 0,
        },
        {
          sampleId: "code-02",
          textClass: "code",
          role: "holdout",
          chars: 477,
          utf8Bytes: 477,
          apiTokens: 166,
          predictedTokens: 166,
          selfContentTokens: 137,
          errorPct: 0,
        },
        {
          sampleId: "code-03",
          textClass: "code",
          role: "calibration",
          chars: 151,
          utf8Bytes: 151,
          apiTokens: 84,
          predictedTokens: 84,
          selfContentTokens: 55,
          errorPct: 0,
        },
        {
          sampleId: "code-04",
          textClass: "code",
          role: "holdout",
          chars: 268,
          utf8Bytes: 268,
          apiTokens: 97,
          predictedTokens: 97,
          selfContentTokens: 68,
          errorPct: 0,
        },
        {
          sampleId: "code-05",
          textClass: "code",
          role: "calibration",
          chars: 182,
          utf8Bytes: 182,
          apiTokens: 83,
          predictedTokens: 83,
          selfContentTokens: 54,
          errorPct: 0,
        },
        {
          sampleId: "code-06",
          textClass: "code",
          role: "holdout",
          chars: 310,
          utf8Bytes: 310,
          apiTokens: 116,
          predictedTokens: 116,
          selfContentTokens: 87,
          errorPct: 0,
        },
        {
          sampleId: "code-07",
          textClass: "code",
          role: "calibration",
          chars: 251,
          utf8Bytes: 251,
          apiTokens: 98,
          predictedTokens: 98,
          selfContentTokens: 69,
          errorPct: 0,
        },
        {
          sampleId: "code-08",
          textClass: "code",
          role: "holdout",
          chars: 297,
          utf8Bytes: 297,
          apiTokens: 128,
          predictedTokens: 128,
          selfContentTokens: 99,
          errorPct: 0,
        },
        {
          sampleId: "code-09",
          textClass: "code",
          role: "calibration",
          chars: 227,
          utf8Bytes: 227,
          apiTokens: 92,
          predictedTokens: 92,
          selfContentTokens: 63,
          errorPct: 0,
        },
        {
          sampleId: "code-10",
          textClass: "code",
          role: "holdout",
          chars: 354,
          utf8Bytes: 354,
          apiTokens: 133,
          predictedTokens: 133,
          selfContentTokens: 104,
          errorPct: 0,
        },
      ],
    },
  ];

/**
 * The article's per-class holdout statistics, for asserting the shipped
 * calibration bands against the source.
 */
export const PER_CLASS: ReadonlyArray<
  Readonly<{
    familyId: string;
    textClass: TextClass;
    holdoutCount: number;
    meanAbsErrorPct: number;
    maxAbsErrorPct: number;
    minBandPct: number;
    maxBandPct: number;
    withinTarget: boolean;
  }>
> = [
  {
    familyId: "anthropic-claude",
    textClass: "english",
    holdoutCount: 5,
    meanAbsErrorPct: 8.98,
    maxAbsErrorPct: 15.56,
    minBandPct: -10.74,
    maxBandPct: 15.56,
    withinTarget: false,
  },
  {
    familyId: "anthropic-claude",
    textClass: "japanese",
    holdoutCount: 5,
    meanAbsErrorPct: 8.15,
    maxAbsErrorPct: 12.88,
    minBandPct: -11.11,
    maxBandPct: 12.88,
    withinTarget: false,
  },
  {
    familyId: "anthropic-claude",
    textClass: "code",
    holdoutCount: 5,
    meanAbsErrorPct: 8.5,
    maxAbsErrorPct: 16.24,
    minBandPct: -7.8,
    maxBandPct: 16.24,
    withinTarget: false,
  },
  {
    familyId: "openai-gpt",
    textClass: "english",
    holdoutCount: 5,
    meanAbsErrorPct: 0,
    maxAbsErrorPct: 0,
    minBandPct: 0,
    maxBandPct: 0,
    withinTarget: true,
  },
  {
    familyId: "openai-gpt",
    textClass: "japanese",
    holdoutCount: 5,
    meanAbsErrorPct: 0,
    maxAbsErrorPct: 0,
    minBandPct: 0,
    maxBandPct: 0,
    withinTarget: true,
  },
  {
    familyId: "openai-gpt",
    textClass: "code",
    holdoutCount: 5,
    meanAbsErrorPct: 0,
    maxAbsErrorPct: 0,
    minBandPct: 0,
    maxBandPct: 0,
    withinTarget: true,
  },
  {
    familyId: "google-gemini",
    textClass: "english",
    holdoutCount: 5,
    meanAbsErrorPct: 5.96,
    maxAbsErrorPct: 11.11,
    minBandPct: -11.11,
    maxBandPct: 8.89,
    withinTarget: false,
  },
  {
    familyId: "google-gemini",
    textClass: "japanese",
    holdoutCount: 5,
    meanAbsErrorPct: 9.37,
    maxAbsErrorPct: 15.73,
    minBandPct: -15.73,
    maxBandPct: 10.96,
    withinTarget: false,
  },
  {
    familyId: "google-gemini",
    textClass: "code",
    holdoutCount: 5,
    meanAbsErrorPct: 4.48,
    maxAbsErrorPct: 8.33,
    minBandPct: -8.33,
    maxBandPct: 5.88,
    withinTarget: false,
  },
  {
    familyId: "oss-qwen",
    textClass: "english",
    holdoutCount: 5,
    meanAbsErrorPct: 0,
    maxAbsErrorPct: 0,
    minBandPct: 0,
    maxBandPct: 0,
    withinTarget: true,
  },
  {
    familyId: "oss-qwen",
    textClass: "japanese",
    holdoutCount: 5,
    meanAbsErrorPct: 0,
    maxAbsErrorPct: 0,
    minBandPct: 0,
    maxBandPct: 0,
    withinTarget: true,
  },
  {
    familyId: "oss-qwen",
    textClass: "code",
    holdoutCount: 5,
    meanAbsErrorPct: 0,
    maxAbsErrorPct: 0,
    minBandPct: 0,
    maxBandPct: 0,
    withinTarget: true,
  },
];

/**
 * The article's edge-case probe readings.
 */
export const EDGE_PROBES: Readonly<{
  anthropicToolOverheadTokens: number;
  anthropicImageTokens: number;
  googleImageTokens: number;
  imageWidth: number;
  imageHeight: number;
}> = {
  anthropicToolOverheadTokens: 483,
  anthropicImageTokens: 124,
  googleImageTokens: 1089,
  imageWidth: 300,
  imageHeight: 300,
};
